# Models - импортировать все чтобы SQLAlchemy видела relationships
from models.user import User
from models.role import Role
from models.order import Order
from models.client import Client
from models.order_part import OrderPart
from models.order_service import OrderService
from models.order_comment import OrderComment
from models.order_payment import OrderPayment
from models.part import Part
from models.service import Service
from models.salary_config import SalaryConfig
from models.salary_record import SalaryRecord
from models.working_hours import WorkingHours
from models.cash_shift import CashShift
from models.cash_transaction import CashTransaction
from models.document_template import DocumentTemplate
from models.document_template_assignment import DocumentTemplateAssignment
from models.notification_task import NotificationTask
from models.bot_settings import BotSettings
from models.permission_group import PermissionGroup
from models.individual_permission import IndividualPermission
from models.role_permission import RolePermission
